"""add_current_step_to_deals

Revision ID: 1c82bdc00d7c
Revises: 6b4ef79baf49
Create Date: 2026-03-14 00:46:05.410313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c82bdc00d7c"
down_revision: str | Sequence[str] | None = "6b4ef79baf49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deals", sa.Column("current_step", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deals", "current_step")
    # ### end Alembic commands ###
